openapi: 3.0.1
info:
  title: Customer Behavior Models
  description: This service domain handles the design and maintenance of a portfolio of customer behavior models that might be used in all aspects of customer relationship development, sales, servicing and product fulfillment
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CustomerBehaviorModels/10.0.0
paths:
  /CustomerBehaviorModels/Create:
    post:
      tags:
      - CR - CustomerBehaviorModelSpecification
      summary: CrCR Create or register an imported customer behavior model
      description: CrCR Create or register an imported customer behavior model
      operationId: Create
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CustomerBehaviorModelSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerBehaviorModelSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CustomerBehaviorModels/{customerbehaviormodelsId}/Execute:
    put:
      tags:
      - CR - CustomerBehaviorModelSpecification
      summary: ExCR Automatically download a customer behavior model
      description: ExCR Automatically download a customer behavior model
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/CustomerBehaviorModelsID'
      requestBody:
        $ref: '#/components/requestBodies/CustomerBehaviorModelSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerBehaviorModelSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CustomerBehaviorModels/{customerbehaviormodelsId}/Request:
    put:
      tags:
      - CR - CustomerBehaviorModelSpecification
      summary: RqCR Request the use of a customer behavior model
      description: RqCR Request the use of a customer behavior model
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/CustomerBehaviorModelsID'
      requestBody:
        $ref: '#/components/requestBodies/CustomerBehaviorModelSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerBehaviorModelSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CustomerBehaviorModels/{customerbehaviormodelsId}/Retrieve:
    get:
      tags:
      - CR - CustomerBehaviorModelSpecification
      summary: ReCR Retrieve details about a customer behavior model
      description: ReCR Retrieve details about a customer behavior model
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CustomerBehaviorModelsID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerBehaviorModelSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CustomerBehaviorModels/Activate:
    post:
      tags:
      - CR - CustomerBehaviorModelSpecification
      summary: UpBQ Update the requirements or other properties of a model
      description: UpBQ Update the requirements or other properties of a model
      operationId: Activate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ActivateCustomerBehaviorModelSpecificationRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivateCustomerBehaviorModelSpecificationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CustomerBehaviorModels/{customerbehaviormodelsId}/FunctionalRequirements/{functionalrequirementsId}/Capture:
    put:
      tags:
      - BQ - FunctionalRequirements
      summary: CaBQ Capture usage reports for a customer behavior model
      description: CaBQ Capture usage reports for a customer behavior model
      operationId: CaptureFunctionalRequirements
      parameters:
      - $ref: '#/components/parameters/CustomerBehaviorModelsID'
      - $ref: '#/components/parameters/FunctionalRequirementsID'
      requestBody:
        $ref: '#/components/requestBodies/CaptureFunctionalRequirementsRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CustomerBehaviorModelSpecification:
      type: object
      properties:
        CustomerBehaviorModelType:
          type: string
        CustomerBehaviorModelPurpose:
          type: string
        CustomerBehaviorModelDeployment:
          type: string
        EmployeeOrBusinessUnitReference:
          type: object
        CustomerBehaviorModelDeploymentConfiguration:
          type: string
        CustomerBehaviorModelDeploymentTaskReference:
          type: object
        CustomerBehaviorModelDeploymentTaskRecord:
          type: string
        CustomerBehaviorModelStatus:
          type: string
        CustomerBehaviorModelUsage:
          type: string
        CustomerBehaviorModelImpact:
          type: string
        CustomerBehaviorModelVersion:
          type: string
        CustomerBehaviorModel:
          type: string
    Testing:
      type: object
      properties:
        CustomerBehaviorModelTestReference:
          type: object
        CustomerBehaviorModelTestType:
          type: string
        CustomerBehaviorModelTestHarnessReference:
          type: object
        CustomerBehaviorModelTestResult:
          type: string
        CustomerBehaviorModelTestingTaskReference:
          type: object
        CustomerBehaviorModelTestingTaskRecord:
          type: string
        CustomerBehaviorModelComplianceTaskReference:
          type: object
        CustomerBehaviorModelComplianceTaskRecord:
          type: string
        CustomerBehaviorModelComplianceTestReference:
          type: object
        CustomerBehaviorModelComplianceTestType:
          type: string
    Production:
      type: object
      properties:
        CustomerBehaviorModelOperationalRequirements:
          type: string
        CustomerBehaviorModelAllowedUsage:
          type: string
        CustomerBehaviorModelUsageGuidelines:
          type: string
    FunctionalRequirements:
      type: object
      properties:
        CustomerBehaviorModelDesignTaskReference:
          type: object
        CustomerBehaviorModelDesignTaskRecord:
          type: string
        Customer/MarketDataServiceReference:
          type: object
        Customer/MarketDataRecord:
          type: string
        CustomerBehaviorModelFeedbackRecord:
          type: string
        CustomerBehaviorModelRequirementsSpecification:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    ActivateCustomerBehaviorModelSpecificationRequest:
      type: object
      properties:
        CustomerBehaviorModelSpecification:
          type: object
          properties:
            CustomerBehaviorModelType:
              type: string
            CustomerBehaviorModelPurpose:
              type: string
            CustomerBehaviorModelStatus:
              type: string
            CustomerBehaviorModelUsage:
              type: string
            CustomerBehaviorModelVersion:
              type: string
            CustomerBehaviorModelImpact:
              type: string
            CustomerBehaviorModelDeployment:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
        FunctionalRequirements:
          type: object
          properties:
            CustomerBehaviorModelDesignTaskReference:
              type: object
            CustomerBehaviorModelDesignTaskRecord:
              type: string
            CustomerBehaviorModelFeedbackRecord:
              type: string
            CustomerBehaviorModelRequirementsSpecification:
              type: string
        Testing:
          type: object
          properties:
            CustomerBehaviorModelTestReference:
              type: object
            CustomerBehaviorModelTestType:
              type: string
            CustomerBehaviorModelTestHarnessReference:
              type: object
            CustomerBehaviorModelTestResult:
              type: string
            CustomerBehaviorModelTestingTaskReference:
              type: object
            CustomerBehaviorModelTestingTaskRecord:
              type: string
    ActivateCustomerBehaviorModelSpecificationResponse:
      type: object
      properties:
        CustomerBehaviorModelSpecification:
          type: object
          properties:
            CustomerBehaviorModelType:
              type: string
            CustomerBehaviorModelPurpose:
              type: string
            CustomerBehaviorModelStatus:
              type: string
            CustomerBehaviorModelUsage:
              type: string
            CustomerBehaviorModelVersion:
              type: string
            CustomerBehaviorModelImpact:
              type: string
            CustomerBehaviorModelDeployment:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerBehaviorModelDeploymentConfiguration:
              type: string
            CustomerBehaviorModelDeploymentTaskReference:
              type: object
            CustomerBehaviorModelDeploymentTaskRecord:
              type: string
        FunctionalRequirements:
          type: object
          properties:
            CustomerBehaviorModelDesignTaskReference:
              type: object
            CustomerBehaviorModelDesignTaskRecord:
              type: string
            CustomerBehaviorModelFeedbackRecord:
              type: string
            CustomerBehaviorModelRequirementsSpecification:
              type: string
            CustomerOrMarketDataServiceReference:
              type: object
            CustomerOrMarketDataRecord:
              type: string
        Testing:
          type: object
          properties:
            CustomerBehaviorModelTestReference:
              type: object
            CustomerBehaviorModelTestType:
              type: string
            CustomerBehaviorModelTestHarnessReference:
              type: object
            CustomerBehaviorModelTestResult:
              type: string
            CustomerBehaviorModelTestingTaskReference:
              type: object
            CustomerBehaviorModelTestingTaskRecord:
              type: string
        Production:
          type: object
          properties:
            CustomerBehaviorModelOperationalRequirements:
              type: string
            CustomerBehaviorModelAllowedUsage:
              type: string
            CustomerBehaviorModelUsageGuidelines:
              type: string
    CaptureFunctionalRequirementsRequest:
      type: object
      properties:
        CustomerBehaviorModelSpecification:
          type: object
          properties:
            CustomerBehaviorModelType:
              type: string
            CustomerBehaviorModelVersion:
              type: string
        FunctionalRequirements:
          type: object
          properties:
            CustomerBehaviorModelFeedbackRecord:
              type: string
  parameters:
    CustomerBehaviorModelsID:
      name: customerbehaviormodelsId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TestingID:
      name: testingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ProductionID:
      name: productionId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    FunctionalRequirementsID:
      name: functionalrequirementsId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    CustomerBehaviorModelSpecification:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomerBehaviorModelSpecification'
    ActivateCustomerBehaviorModelSpecificationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActivateCustomerBehaviorModelSpecificationRequest'
    CaptureFunctionalRequirementsRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaptureFunctionalRequirementsRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
