openapi: 3.0.1
info:
  title: Location Data Management
  description: This service domain maintain details of the use and state of locations of interest to the bank. This can include both physical and virtual addresses. It is used to check for valid use and for sales/marketing activities
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/LocationDataManagement/10.0.0
paths:
  /LocationDataManagement/Activate:
    post:
      tags:
      - CR - LocationDirectoryEntry
      summary: InCR Register a location in the catalog
      description: InCR Register a location in the catalog
      operationId: Activate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ActivateLocationDirectoryEntryRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivateLocationDirectoryEntryResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    LocationDirectoryEntry:
      type: object
      properties:
        LocationReference:
          type: object
        DateType:
          type: string
        Date:
          type: string
    Use:
      type: object
      properties:
        LocationZoningType:
          type: string
        LocationUsage:
          type: string
    Occupancy:
      type: object
      properties:
        CustomerReference:
          type: object
        LocationOwner/Title:
          type: string
        LocationValue:
          type: string
        LocationOccupierType:
          type: string
        LocationOccupierReference:
          type: object
        LocationOccupierTerms:
          type: string
        AlliancePartnerReference:
          type: object
    Location:
      type: object
      properties:
        LocationType:
          type: string
        LocationAddress:
          type: string
        LocationCoordinates:
          type: string
        LocationDescription:
          type: string
        LocationConstructionType:
          type: string
        LocationCapacity:
          type: string
        LocationStatus:
          type: string
        LocationNeighborhoodType:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    ActivateLocationDirectoryEntryRequest:
      type: object
      properties:
        LocationDirectoryEntry:
          type: object
          properties:
            LocationReference:
              type: object
            DateType:
              type: string
            Date:
              type: string
        Location:
          type: object
          properties:
            LocationType:
              type: string
            LocationAddress:
              type: string
            LocationCoordinates:
              type: string
            LocationDescription:
              type: string
            LocationConstructionType:
              type: string
            LocationCapacity:
              type: string
            LocationStatus:
              type: string
            LocationNeighborhoodType:
              type: string
        Use:
          type: object
          properties:
            LocationZoningType:
              type: string
            LocationUsage:
              type: string
        Occupancy:
          type: object
          properties:
            CustomerReference:
              type: object
            LocationOwnerOrTitle:
              type: string
            LocationValue:
              type: string
            LocationOccupierType:
              type: string
            LocationOccupierReference:
              type: object
            LocationOccupierTerms:
              type: string
            AlliancePartnerReference:
              type: object
    ActivateLocationDirectoryEntryResponse:
      type: object
      properties:
        LocationDirectoryEntry:
          type: object
          properties:
            LocationReference:
              type: object
            DateType:
              type: string
            Date:
              type: string
        Location:
          type: object
          properties:
            LocationType:
              type: string
            LocationAddress:
              type: string
            LocationCoordinates:
              type: string
            LocationDescription:
              type: string
            LocationConstructionType:
              type: string
            LocationCapacity:
              type: string
            LocationStatus:
              type: string
            LocationNeighborhoodType:
              type: string
        Use:
          type: object
          properties:
            LocationZoningType:
              type: string
            LocationUsage:
              type: string
        Occupancy:
          type: object
          properties:
            CustomerReference:
              type: object
            LocationOwnerOrTitle:
              type: string
            LocationValue:
              type: string
            LocationOccupierType:
              type: string
            LocationOccupierReference:
              type: object
            LocationOccupierTerms:
              type: string
            AlliancePartnerReference:
              type: object
  parameters:
    LocationDataManagementID:
      name: locationdatamanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    UseID:
      name: useId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    OccupancyID:
      name: occupancyId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    LocationID:
      name: locationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ActivateLocationDirectoryEntryRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActivateLocationDirectoryEntryRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
