openapi: 3.0.1
info:
  title: Regulatory Reporting
  description: This service domain administers and orchestrates the tasks required to meet the bank's regulatory reporting obligations
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/RegulatoryReporting/10.0.0
paths:
  /RegulatoryReporting/Activate:
    post:
      tags:
      - CR - RegulatoryComplianceAdministrativePlan
      summary: UpCR Update the regulatory reporting set up or schedule
      description: UpCR Update the regulatory reporting set up or schedule
      operationId: Activate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ActivateRegulatoryComplianceAdministrativePlanRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegulatoryComplianceAdministrativePlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    RegulatoryComplianceAdministrativePlan:
      type: object
      properties:
        RegulatoryAuthorityReference:
          type: object
        RegulatoryReportingSchedule:
          type: string
        RegulationReference:
          type: object
        RegulatoryReportType:
          type: string
    Consolidation:
      type: object
      properties:
        RegulatoryReportTypeContentRequirements:
          type: string
        SourceBusinessUnit/EmployeeReference:
          type: object
        SourceProductandServiceReference:
          type: object
        SourceCustomerReference:
          type: object
        SourceTransactionRecords:
          type: string
    Enquiries:
      type: object
      properties:
        RegulatoryEnquiry:
          type: string
        EnquiryBusinessUnitReference:
          type: object
        EnquiryProductandServiceReference:
          type: object
        EnquiryCustomerReference:
          type: object
        EnquiryTransactionRecords:
          type: string
        RegulatoryEnquiryWorkProducts:
          type: string
        RegulatoryEnquiryResult:
          type: string
        RegulatoryEnquiryDocumentReference:
          type: object
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    ActivateRegulatoryComplianceAdministrativePlanRequest:
      type: object
      properties:
        RegulatoryComplianceAdministrativePlan:
          type: object
          properties:
            RegulatoryAuthorityReference:
              type: object
            RegulatoryReportingSchedule:
              type: string
            RegulationReference:
              type: object
            RegulatoryReportType:
              type: string
        Consolidation:
          type: object
          properties:
            SourceTransactionRecords:
              type: string
            SourceBusinessUnitOrEmployeeReference:
              type: object
            SourceProductandServiceReference:
              type: object
        Enquiries:
          type: object
          properties:
            RegulatoryEnquiry:
              type: string
            EnquiryBusinessUnitReference:
              type: object
            EnquiryProductandServiceReference:
              type: object
            EnquiryCustomerReference:
              type: object
            EnquiryTransactionRecords:
              type: string
  parameters:
    RegulatoryReportingID:
      name: regulatoryreportingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ConsolidationID:
      name: consolidationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    EnquiriesID:
      name: enquiriesId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ActivateRegulatoryComplianceAdministrativePlanRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActivateRegulatoryComplianceAdministrativePlanRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
